add_subdirectory(shared)

function(libcommuni_add_autotest)
    libcommuni_add_test(${ARGV})
    target_link_libraries(${test_name} PRIVATE LibCommuniAutotestShared)
endfunction()

add_subdirectory(irc)
add_subdirectory(ircbuffer)
add_subdirectory(ircbuffermodel)
add_subdirectory(ircchannel)
add_subdirectory(irccommand)
add_subdirectory(irccommandparser)
add_subdirectory(irccommandqueue)
add_subdirectory(irccompleter)
add_subdirectory(ircconnection)
add_subdirectory(irclagtimer)
add_subdirectory(ircmessage)
add_subdirectory(ircnetwork)
add_subdirectory(ircpalette)
add_subdirectory(irctextformat)
add_subdirectory(ircuser)
add_subdirectory(ircusermodel)
